# rust-actions-toolkit v2.1.1 configuration for py2pyd
# This configuration optimizes builds and release artifacts

[project]
name = "py2pyd"
description = "A Rust-based tool to compile Python modules to pyd files"
binary-name = "py2pyd"

[build]
# Rust toolchain configuration
rust-toolchain = "stable"
# Enable zero-dependency builds
static-linking = true
# Optimize for size and performance
optimize = true
strip = true

[targets]
# Zero-dependency Windows builds
windows = [
    "x86_64-pc-windows-gnu",
    "i686-pc-windows-gnu"
]

# Static Linux builds
linux-musl = [
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-musl"
]

# Standard Linux builds
linux-gnu = [
    "x86_64-unknown-linux-gnu",
    "aarch64-unknown-linux-gnu"
]

# macOS builds (native runners)
macos = [
    "x86_64-apple-darwin",
    "aarch64-apple-darwin"
]

[release]
# Release artifact configuration
create-archives = true
archive-format = "auto"  # zip for Windows, tar.gz for Unix
include-readme = true
include-license = true

# Archive naming
archive-name-template = "{binary-name}-{target}"

# Release notes
generate-release-notes = true
draft = false
prerelease = false

[environment]
# Environment variables for zero-dependency builds
RUSTFLAGS = "-C target-feature=+crt-static"
OPENSSL_STATIC = "1"
PKG_CONFIG_ALLOW_CROSS = "1"

[cache]
# Enable caching for faster builds
enabled = true
key-prefix = "py2pyd-v2.1.1"

[verification]
# Verify zero dependencies for specific targets
verify-static = ["*-musl", "*-windows-gnu"]
verify-commands = [
    "ldd {binary} || echo 'Static binary'",
    "file {binary}"
]
