[workspace]
# Enable automatic changelog generation
changelog_update = true
# Disable workspace-level GitHub releases (handled by package level)
git_release_enable = false
# Enable automatic tag creation
git_tag_enable = true
# Enable processing for releases
release = true
# Disable publishing to crates.io at workspace level
publish = false

# Changelog configuration
[changelog]
header = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

"""

# Package-specific configuration for py2pyd
[[package]]
name = "py2pyd"
# Enable changelog updates
changelog_update = true
# Enable GitHub releases for the main package
git_release_enable = true
# Enable processing for releases
release = true
# Standard tag format (triggers release workflows)
git_tag_name = "v{{version}}"
# Don't publish to crates.io (this is a binary tool)
publish = false
# Allow major version bumps for breaking changes
allow_dirty = false
# Ensure proper semantic versioning
semver_check = true
# Release draft mode (false for automatic releases)
git_release_draft = false
# Include pre-release versions
git_release_latest = true
