# Cargo configuration for cross-compilation

# Windows GNU targets - disable mimalloc to avoid MinGW compilation issues
[target.x86_64-pc-windows-gnu]
rustflags = [
    "-C", "link-arg=-Wl,--allow-multiple-definition",
]

[target.i686-pc-windows-gnu]
rustflags = [
    "-C", "link-arg=-Wl,--allow-multiple-definition",
]

# Environment variables for Windows GNU targets
[env]
# These will be set for all builds, but our build.rs will override them appropriately
CARGO_FEATURE_MIMALLOC = { value = "0", condition = "cfg(any(target = \"x86_64-pc-windows-gnu\", target = \"i686-pc-windows-gnu\"))" }
MIMALLOC_OVERRIDE = { value = "0", condition = "cfg(any(target = \"x86_64-pc-windows-gnu\", target = \"i686-pc-windows-gnu\"))" }