[build]
# Use sccache for faster builds
# rustc-wrapper = "sccache"

# Enable parallel compilation
jobs = 8

# Enable incremental compilation
incremental = true

# Target-specific configurations removed to avoid proc-macro compilation issues
# These can be re-enabled later if needed for specific optimizations

[profile.release]
# Conservative optimization settings to avoid proc-macro issues
opt-level = 3
codegen-units = 1
