name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  ci:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-ci.yml@v1
    with:
      rust-toolchain: stable
      enable-coverage: true
      enable-python-wheel: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}




