name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    container: ghcr.io/loonghao/rust-toolkit:base
    steps:
      - uses: actions/checkout@v4

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - uses: loonghao/rust-actions-toolkit@v2.0.2
        with:
          command: ci
          rust-toolchain: stable
          check-format: true
          check-clippy: true
          check-docs: true
          clippy-args: '--all-targets --all-features -- -D warnings'
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


