name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Rust version
        run: |
          echo "🦀 Checking Rust version for malachite compatibility..."
          rustc --version
          echo "📦 Cargo version:"
          cargo --version
        shell: bash

      - name: Run CI checks
        uses: loonghao/rust-actions-toolkit@v2.0.2
        with:
          command: ci
          rust-toolchain: stable
          clippy-args: '--all-targets --all-features -- -D warnings -A clippy::too_many_lines -A clippy::uninlined_format_args -A clippy::format_push_string'


