name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Use reusable CI workflow from rust-actions-toolkit (includes code quality checks)
  ci:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-ci.yml@v4.0.0
    with:
      # Rust toolchain version
      rust-toolchain: stable
      # Enable coverage reporting
      enable-coverage: false
      # Disable Python wheel testing for this project
      enable-python-wheel: false
      # Additional target platforms for zero-dependency testing
      additional-targets: |
        [
          {"target": "x86_64-pc-windows-gnu", "os": "ubuntu-22.04"},
          {"target": "i686-pc-windows-gnu", "os": "ubuntu-22.04"},
          {"target": "x86_64-unknown-linux-musl", "os": "ubuntu-22.04"},
          {"target": "aarch64-unknown-linux-musl", "os": "ubuntu-22.04"}
        ]


