name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: loonghao/rust-actions-toolkit@v1.1.6
        with:
          command: ci
          rust-toolchain: stable
          check-format: true
          check-clippy: true
          check-docs: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}


