name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  actions: read
  security-events: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Use reusable CI workflow from rust-actions-toolkit (includes code quality checks)
  ci:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-ci.yml@v2.3.2
    with:
      # Rust toolchain version
      rust-toolchain: stable
      # Enable coverage reporting
      enable-coverage: false
      # Disable Python wheel testing for this project
      enable-python-wheel: false

      # 🚀 Enable release build testing for CI/Release consistency
      test-release-builds: true
      build-depth: release

      # Target platforms that match release.yml for consistency
      release-target-platforms: |
        [
          {"target": "x86_64-pc-windows-gnu", "os": "ubuntu-22.04"},
          {"target": "i686-pc-windows-gnu", "os": "ubuntu-22.04"},
          {"target": "x86_64-unknown-linux-musl", "os": "ubuntu-22.04"},
          {"target": "aarch64-unknown-linux-musl", "os": "ubuntu-22.04"}
        ]

      # Legacy additional targets (for backward compatibility)
      additional-targets: |
        [
          {"target": "x86_64-pc-windows-gnu", "os": "ubuntu-22.04"},
          {"target": "i686-pc-windows-gnu", "os": "ubuntu-22.04"},
          {"target": "x86_64-unknown-linux-musl", "os": "ubuntu-22.04"},
          {"target": "aarch64-unknown-linux-musl", "os": "ubuntu-22.04"}
        ]




