name: Release-plz

on:
  push:
    branches:
      - main

jobs:
  release:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-release-plz.yml@v1
    with:
      # Optional: Customize Rust toolchain
      rust-toolchain: stable
      # Optional: Specify release-plz version
      release-plz-version: v0.5
    secrets:
      # Required: For crates.io publishing (if you publish Rust crates)
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      # Required: For GitHub operations
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Optional: Enhanced GitHub PAT for cross-workflow triggers
      # This allows release-plz to trigger other workflows (like release.yml)
      RELEASE_PLZ_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}