name: Release-plz

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-plz:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_TOKEN || secrets.GITHUB_TOKEN }}

      - uses: loonghao/rust-actions-toolkit@v1.2.0
        with:
          command: release-plz
          rust-toolchain: stable
          release-plz-command: both
          cargo-registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          release-plz-token: ${{ secrets.RELEASE_PLZ_TOKEN }}
  