name: Release-plz

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  release-plz:
    uses: loonghao/rust-actions-toolkit/.github/workflows/reusable-release-plz.yml@master
    with:
      rust-toolchain: 'stable'
      release-plz-version: 'v0.5'
    secrets:
      RELEASE_PLZ_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}