name: Semantic Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'
      - '.github/workflows/**'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: "0"

jobs:
  semantic-version:
    name: Determine Semantic Version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.version.outputs.new_version }}
      version_changed: ${{ steps.version.outputs.changed }}
      release_type: ${{ steps.version.outputs.release_type }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine version bump
        id: version
        run: |
          # Get current version from Cargo.toml
          CURRENT_VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "Current version: $CURRENT_VERSION"
          
          # Parse version components
          IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT_VERSION"
          
          # Get commit messages since last tag
          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
            COMMITS=$(git log --pretty=format:"%s" --no-merges)
          else
            COMMITS=$(git log ${LAST_TAG}..HEAD --pretty=format:"%s" --no-merges)
          fi
          
          echo "Analyzing commits:"
          echo "$COMMITS"
          
          # Determine release type based on conventional commits
          RELEASE_TYPE="none"
          
          # Check for breaking changes (major version bump)
          if echo "$COMMITS" | grep -qE "(BREAKING CHANGE|!:)"; then
            RELEASE_TYPE="major"
            NEW_MAJOR=$((MAJOR + 1))
            NEW_MINOR=0
            NEW_PATCH=0
          # Check for features (minor version bump)
          elif echo "$COMMITS" | grep -qE "^feat(\(.+\))?:"; then
            RELEASE_TYPE="minor"
            NEW_MAJOR=$MAJOR
            NEW_MINOR=$((MINOR + 1))
            NEW_PATCH=0
          # Check for fixes (patch version bump)
          elif echo "$COMMITS" | grep -qE "^fix(\(.+\))?:"; then
            RELEASE_TYPE="patch"
            NEW_MAJOR=$MAJOR
            NEW_MINOR=$MINOR
            NEW_PATCH=$((PATCH + 1))
          # Check for other conventional commit types that should trigger patch
          elif echo "$COMMITS" | grep -qE "^(docs|style|refactor|perf|test|chore)(\(.+\))?:"; then
            RELEASE_TYPE="patch"
            NEW_MAJOR=$MAJOR
            NEW_MINOR=$MINOR
            NEW_PATCH=$((PATCH + 1))
          fi
          
          if [ "$RELEASE_TYPE" != "none" ]; then
            NEW_VERSION="${NEW_MAJOR}.${NEW_MINOR}.${NEW_PATCH}"
            echo "Release type: $RELEASE_TYPE"
            echo "New version: $NEW_VERSION"
            echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
            echo "changed=true" >> $GITHUB_OUTPUT
            echo "release_type=$RELEASE_TYPE" >> $GITHUB_OUTPUT
          else
            echo "No version bump needed"
            echo "new_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
            echo "changed=false" >> $GITHUB_OUTPUT
            echo "release_type=none" >> $GITHUB_OUTPUT
          fi

  update-version:
    name: Update Version
    needs: semantic-version
    if: needs.semantic-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Cargo.toml version
        run: |
          NEW_VERSION="${{ needs.semantic-version.outputs.new_version }}"
          sed -i "s/version = \"[0-9]*\.[0-9]*\.[0-9]*\"/version = \"$NEW_VERSION\"/" Cargo.toml
          
          # Verify the change
          UPDATED_VERSION=$(grep '^version = ' Cargo.toml | head -1 | sed 's/version = "\(.*\)"/\1/')
          echo "Updated version to: $UPDATED_VERSION"

      - name: Commit version update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Cargo.toml
          git commit -m "bump: version ${{ needs.semantic-version.outputs.new_version }} [skip ci]

Automatic version bump based on conventional commits.
Release type: ${{ needs.semantic-version.outputs.release_type }}

Signed-off-by: github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          git push

  build-and-release:
    name: Build and Release
    needs: [semantic-version, update-version]
    if: needs.semantic-version.outputs.version_changed == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: py2pyd.exe
            asset_name: py2pyd-windows-x86_64.zip
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: py2pyd
            asset_name: py2pyd-linux-x86_64.tar.gz
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: py2pyd
            asset_name: py2pyd-macos-x86_64.tar.gz
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: py2pyd
            asset_name: py2pyd-macos-aarch64.tar.gz

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # Get the updated version

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Setup MSVC (Windows)
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install build dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev

      - name: Setup sccache
        uses: mozilla-actions/sccache-action@v0.0.9

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
        env:
          SCCACHE_GHA_ENABLED: "true"
          RUSTC_WRAPPER: "sccache"

      - name: Create Release Archive (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          mkdir release
          copy target\${{ matrix.target }}\release\${{ matrix.artifact_name }} release\
          copy README.md release\
          copy LICENSE release\
          Compress-Archive -Path release\* -DestinationPath ${{ matrix.asset_name }}

      - name: Create Release Archive (Unix)
        if: matrix.os != 'windows-latest'
        run: |
          mkdir release
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} release/
          cp README.md release/
          cp LICENSE release/
          if [[ "${{ matrix.asset_name }}" == *.tar.gz ]]; then
            tar -czf ${{ matrix.asset_name }} -C release .
          else
            zip -r ${{ matrix.asset_name }} release/
          fi

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.asset_name }}
          if-no-files-found: error

  create-release:
    name: Create GitHub Release
    needs: [semantic-version, update-version, build-and-release]
    if: needs.semantic-version.outputs.version_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main  # Get the updated version

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Git Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v${{ needs.semantic-version.outputs.new_version }}
          git push origin v${{ needs.semantic-version.outputs.new_version }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.semantic-version.outputs.new_version }}
          name: Release v${{ needs.semantic-version.outputs.new_version }}
          files: |
            artifacts/x86_64-pc-windows-msvc/py2pyd-windows-x86_64.zip
            artifacts/x86_64-unknown-linux-gnu/py2pyd-linux-x86_64.tar.gz
            artifacts/x86_64-apple-darwin/py2pyd-macos-x86_64.tar.gz
            artifacts/aarch64-apple-darwin/py2pyd-macos-aarch64.tar.gz
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
